### ISSUE TITLE
hmtl between gauges?

### ISSUE THREAD

**Issue by rurounijones** [CoralineAda/seer#4]
Is it possible to have an option to add elements between each gauge image? For example to let people add a break tag to make a vertical list or add an image separator etc.

**Comment by rurounijones** [comment]
Ah, I just saw that the gauges are arranged in an HTML table. Is this controlled by google or would it be possible for seer to return a collection of erb objects so that we could lay them out how we wish?

**Comment by vanboom** [comment]
The table also truncates long gage titles - it would be nice if the table would auto-size to the width of the title text and not just the span of the gage.
